import { FaRegHeart } from "react-icons/fa";
import { FaHeart } from "react-icons/fa6";
import img1 from "../../../Assets/mywishlist image1.png";
export const MyWishlistData = [
  {
    id: 1,
    image:
      img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 2,
    image:
    img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 3,
    image:
      img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 4,
    image:
      img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 5,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 6,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 7,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 8,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 9,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 10,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 11,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 12,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 13,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 14,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 15,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 16,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
  {
    id: 17,
    image: img1,
    name: "LuvLap Silicone FoodFruit Nibbler with Extra Mesh, Soft Pacifier/Feeder, Teether for Baby, Infant, Bunny Violet & Pink",
    mrp: "MRP: ₹199",
    secondmrp: "₹ 154",
    off: "23% Off",
    // icon: <FaRegHeart />,
    icon2: <FaHeart />,
  },
];
